services:
  git-backup:
    image: registry.neureka.dev/git/backup:edge
    container_name: git-backup
    env_file:
      - .env
    networks:
      - git-backup
    volumes:
      - ./settings.yaml:/app/data/settings.yaml:ro
    restart: unless-stopped

networks:
  git-backup:
    name: git-backup
