services:
  git-backup:
    image: registry.neureka.dev/git/git-backup:edge
    container_name: git-backup
    env_file:
      - .env
    networks:
      - git-backup
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  git-backup:
    name: git-backup
